# Site settings
title: Department of Mathematical Modeling of Heterogeneous System
email: matmodel2013@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Address: 119333, Russia, Moscow, 40 Vavilova str., R. 121, 121A, 122<br>
  Phone: +7(495)938-28-67<br>
  Fax: +7(499)135-61-59

baseurl: "/ccasen" # the subpath of your site, e.g. /blog/
url: "http://iskolbin.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
